### ISSUE TITLE
how to analyze potential memory issue

### ISSUE THREAD

**Issue by markfink** [MarioViara/xprintfc#3]
thank you so much for this terrific module! This issue is most likely not a problem with your code and perhaps a user question. You did not state if or how you would like to address these so I hope you do not mind that I put it in here.

I am using your library on a LPC1343 in a FreeRTOS context. I believe my FreeRTOS configuration works stable since I can ran tasks and queues for hours. I am working on a serial "CLI'". My xprintf also runs stable-ish. But once I use xformatc my application immediately hangs.

The test suite for xformatc has 70% code coverage so I am confident that I did not mess up your code base. Currently I do not feel very confident to debug the embedded FreeRTOS setting I have so I hope you would share some tips for trouble-shooting with me.

I should probably state that I run version 1.01 of your code.

the xprintf function I came up with:
```
#include <stdarg.h>
#include "xprintf.h"
#include "xformatc.h"
#include "uart.h"

static void put_char(void *arg, char c) {
  //UARTSendChar((uint8_t) c);
  UARTSendChar(c);
}

void xprintf(const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  xvformat(put_char, NULL, fmt, args);
  va_end(args);
}

void xvprintf(const char *fmt, va_list _args) {
  //va_list args;
  //va_copy(args, _args);
  xvformat(put_char, NULL, fmt, _args);
  //va_end(args);
}
```

**Comment by MarioViara** [comment]
Hello Mark,
I use this routine in namy project with ARM and FreeRTOS wo i'm sure it works. I think the problem is the stack usage the default configuration name floating point number and long long integer and require around 400 bytes of stack. Try to compile your project with this define 

To disable the long long support 
 -DXCFG_FORMAT_LONGLONG=0 

To disable the floaing point support
 -DXCFG_FORMAT_FLOAT

And as last resource if you use the printf only from one thread with this define

XCFG_FORMAT_STATIC=static

The printf function became non reentrant (SO CANNOT BE USED FROM MORE THAN ONE THREAD) but it will reduce the stack usage.

Let me know the result of your test
best regards
Mario Viara

**Comment by markfink** [comment]
Hi Mario, 
thank you for this explanation. "XCFG_FORMAT_STATIC=static" makes the problem go away. In my experience printing from multiple threads messes up the output so I won't miss it much. But I will keep the restriction in mind. Again thank you for your help.
Best,
Mark
